### ISSUE TITLE
receive.cgi takes date literally

### ISSUE THREAD

**Issue by spotlightishere** [RiiConnect24/Mail-Go#1]
No formatting is applied for the time boundary.

...should this even be fixed? During testing, the Wii downloaded the mail successfully and sent a delete request as expected.

**Comment by pokeacer** [comment]
The time boundary could literally be random characters if it works. It doesn't care as long as it's a valid MIME boundary. Semantically it'd make more sense but tbh it doesn't _really_ matter.

**Comment by spotlightishere** [comment]
This should probably be low priority then.

eta fix soon™

**Comment by larsenv** [comment]
Fixed this in the latest commits.
