### ISSUE TITLE
Check if a Wii Number is valid or not

### ISSUE THREAD

**Issue by larsenv** [RiiConnect24/Mail-Go#14]
When registering a Wii in the account database, we should use the algorithm Nintendo used to determine whether a Wii Number is valid or not.

Based on some RE, it seems the Wii Number can be scrambed and unscrambled.

**Comment by spotlightishere** [comment]
I don't think it'd be hard to figure out, this just hasn't been investigated. We should find a way to collaborate if it isn't found ourselves.

**Comment by InternalLoss** [comment]
We still haven't worked out how to validate Wii FCs iirc; if we do then awesome.

**Comment by larsenv** [comment]
Forgot this was open, the Wii Number validation has been added in late January of this year.

[Source code is here.](https://github.com/RiiConnect24/wiino)
