### ISSUE TITLE
Make sure send script is sending mail to Wii Numbers in the database

### ISSUE THREAD

**Issue by larsenv** [RiiConnect24/Mail-Go#15]
This might be an easy fix - it would be a good idea to not let mail send if a Wii is trying to send to a Wii Number that's not in the accounts database. That way, mail for Wiis that aren't connected to RiiConnect24 won't have to be stuck in our database.

I believe if we give an error code saying it can't send to that Wii Number, it might get stuck in the Wii's mailbox, so we should look into that.

**Comment by KcrPL** [comment]
I think that it would be better to just receive and delete it from the database then just keep it in Wii's memory.

**Comment by spotlightishere** [comment]
Currently I believe we silently ignore it and return success.

**Comment by larsenv** [comment]
Yeah that's what I was thinking ^

**Comment by KcrPL** [comment]
Was Nintendo even checking it?

**Comment by spotlightishere** [comment]
I'm not entirely sure, but I've never heard of them returning an error code for adding some random user. I'd take a guess and say they silently ignored it as well.

**Comment by larsenv** [comment]
According to an error code list, response 351 is returned when a mail is trying to be sent to an invalid address.
