### ISSUE TITLE
Challenge Response for check script

### ISSUE THREAD

**Issue by larsenv** [RiiConnect24/Mail-Go#16]
This is something we've been trying to get working for a long time - on the check script, we should output the correct hash for the challenge response it has. The hash seems to be an HMAC SHA1. The Wii sends some bytes to the server which has to do with it, it's called a challenge code (abbreviated to "chlng").

IOS31 and IOS80 are patched to get rid of the challenge response check (thus, not giving error 102032, which means hash verification failed). However, when a game tries to send mail that uses a different IOS, you still get the error since it's not patched. That's why I want to get it figured out.

**Comment by InternalLoss** [comment]
NOW OFFICIALLY FIXED. :heart:
