### ISSUE TITLE
Find difference between mlnum and allnum response in receive

### ISSUE THREAD

**Issue by larsenv** [RiiConnect24/Mail-Go#18]
We should do some RE to find the difference between these. Is only mlnum used? We'll have to figure it out.

**Comment by spotlightishere** [comment]
Both are used.

Inferred from IOS 80:
It seems that Nintendo expects the maximum mail size returned to be 65535 bytes maximum. Anything more and the server would hold back messages. `mlnum` is the amount of messages sent in that request, and `allnum` is the amount still left. It appears it may repeat the process however I'm not certain, quickly looked at it.
