### ISSUE TITLE
Prevent Duplicate Account Registration

### ISSUE THREAD

**Issue by JonM313** [RiiConnect24/Mail-Go#20]
Normally someone would have to be removed from the database to re-register or they'll get 1102y1 (Duplicate Account Registration). I think I know something to prevent that. What if you can make it where if the database sees that a console is trying to register for a second time it overwrites the initial account with the second account? Idk if I said it clear enough but I said it as clear and I can. Hopefully this was the right place to put this.

**Comment by spotlightishere** [comment]
We want to keep how it is as we don't want exactly that. There is currently no good way for us to keep track of who is registered as what, and we don't want to revoke a legitimate user's access because someone faked their Wii.
