### ISSUE TITLE
Wrong domain

### ISSUE THREAD

**Issue by spotlightishere** [RiiConnect24/Mail-Go#22]
For some reason, despite connecting to our servers, `@rc24.xyz` email are still shown as `@wii.com`. Why? I've personally been unable to reproduce this however have seen others do this.

**Comment by jakerules** [comment]
I've gotten this as well. Here is a picture of the emails I got and they were sent at different times but were delivered at the same time. 
![image](https://user-images.githubusercontent.com/6377830/41062201-1908cb1c-69a3-11e8-9a8f-b59ddc207114.png)

**Comment by KcrPL** [comment]
![123](https://user-images.githubusercontent.com/17184296/41064165-ff15dfb4-69da-11e8-8c18-41ba690a250c.JPG)

Interresting... ^ this is a mail from month ago.

**Comment by spotlightishere** [comment]
I asked @jakerules to send me their `/shared2/wc24` folder, in hopes we could find something.

Scanning through `wc24send.mbx`, I see the mail is composed as `@wii.com`. Considering the Wii System Menu puts the mail together, it makes me wonder if wii.com is specified as the sender and we never noticed it? The date matches correctly.

Since 5643d9c6d9506c9508ee8d1daa03575765cadd2e we've manually changed the sent email from wii.com to rc24.xyz due to Nintendo hardcoding the message. It may be this issue has always happened and the difference is causing people to notice.

**Comment by larsenv** [comment]
I think I found the problem - it wants the To address on the Wii to be like `To: w9999999999990000@rc24.xyz` instead of `To: "w9999999999990000@rc24.xyz" <w9999999999990000@rc24.xyz>`.

**Comment by caution3** [comment]
This issue should be closed as it was fixed in commit 5643d9c6d9506c9508ee8d1daa03575765cadd2e iirc.
