### ISSUE TITLE
Fix memory leak

### ISSUE THREAD

**Issue by larsenv** [RiiConnect24/Mail-Go#24]
There's currently a bad memory leak that occurs because MySQL connections aren't closed somewhere, and eventually causes the mail server to crash.

That's all.

**Comment by larsenv** [comment]
[I am certain this line of code is where the memory leak is happening.](https://github.com/RiiConnect24/Mail-Go/blob/master/wiimail.go#L100)

**Comment by spotlightishere** [comment]
It's actually here:
https://github.com/RiiConnect24/Mail-Go/blob/bc1ed26fc4fc15a7c67c3ddde3136b94d8d03834/inbound_parse.go#L76-L88

The database connection is not closed after usage, keeping the queue open.

**Comment by larsenv** [comment]
The mail script hasn't crashed ever since ae1e997ddd6c3022134fc80fcddf0532474e810a, so I'm gonna close this.
