### ISSUE TITLE
Conversion of Images to JPEG for Wii.

### ISSUE THREAD

**Issue by spotlightishere** [RiiConnect24/Mail-Go#3]
The Wii only supports JPEGs via Wii Mail. I've noticed some users sending PNGs and GIFs via email <-> Wii.

In the future, it should be decided if we want to convert dynamically or just leave it be as current (ignoring non-JPEG files).

**Comment by KcrPL** [comment]
Well, not every user know that Wii only supports .JPEG files. They would be thinking why the picture isn't appearing on Wii so I say we should convert pictures.

**Comment by spotlightishere** [comment]
That would be a major reason for, against would be processing power and selecting a proper conversation library.

**Comment by KcrPL** [comment]
`processing power` - That wouldn't be a problem. You could make an convertion script on VPS so it could handle it one at the time, right?

**Comment by spotlightishere** [comment]
We'd want this all to be done in the program. Too many images would overload the entire program for all, so we need to meet specific requirements.

**Comment by pokeacer** [comment]
Regarding conversion, we could resize the image to a set resolution, and compress using enough JPEG compression to immensely reduce the size needed, but not so much that it's not viewable.

A viable solution is Discord's own https://github.com/discordapp/lilliput, written in Go itself, that can do these things on a massive scale that Discord requires.

**Comment by KcrPL** [comment]
```Lilliput relies on mature, high-performance C libraries to do most of the work of decompressing, resizing and compressing images. It aims to do as little memory allocation as possible and especially not to create garbage in Go. As a result, it is suitable for very high throughput image resizing services.``` 

Hell yeah.

**Comment by spotlightishere** [comment]
More or less done in a91498af0ff2ef009899c778cc279c122e8340c2. We use a fork of Lilliput in order to support the Alpine Linux image libgcc/libstdc++ and muslc.

**Comment by pokeacer** [comment]
Just seen this; this is amazing, thank you for your tireless work :heart:
