### ISSUE TITLE
Connect to Sentry

### ISSUE THREAD

**Issue by spotlightishere** [RiiConnect24/Mail-Go#4]
Current mail scripts allow status and error reporting.
This will need to be added.

**Comment by spotlightishere** [comment]
I'm gonna move this to Test Stage as I can't test this indev.

**Comment by spotlightishere** [comment]
Due to the above reason, this needs to be figured out. I suggest an optional config.json key.

**Comment by larsenv** [comment]
I updated the issue name since we don't use Cachet anymore.

**Comment by spotlightishere** [comment]
Implemented in `d41147a3a7cc68a60ee59681447d445a3837fd80` and `1693350f64ae33ca58ba49ec4bf3bc264aafb114`.
